import { comparisons } from '@/lib/comparisons'

export const dynamic = 'force-static'

const baseUrl = 'https://articlos.com'

function body(): string {
  const compareLines = comparisons.map((c) =>
    `- [articlos vs ${c.competitor}](${baseUrl}/compare/vs-${c.slug}): ${c.hubBlurb}`
  ).join('\n')

  return `# articlos

> articlos is the closed-loop content intelligence system that discovers what to write from your Search Console data, generates SEO + AEO-optimized articles with your brand voice, publishes them directly to WordPress, tracks rankings, and rewrites decaying content — automatically.

articlos runs the full content operation end-to-end: keyword opportunity discovery, topic planning, AI article generation, WordPress publishing with auto internal linking, keyword rank tracking, content-decay detection via GA4, and automated rewrites when articles lose traffic. It is not a blank text box — it is a system that runs your content marketing while you focus on strategy.

articlos uses GPT, Claude, and Gemini under the hood, picking the best model per article and falling back when one provider has an outage. Every article is generated in your brand voice (trained from samples of your existing content), includes auto-generated metadata, JSON-LD structured data, internal link suggestions validated against your post URLs, and a featured image from Pexels. The Autopilot plan runs the entire pipeline on a weekly cron — topic → draft → published post with zero manual steps.

## Docs

- [Features](${baseUrl}/features): Every feature grouped by the six-stage loop — Discover, Plan, Generate, Publish, Measure, Improve
- [FAQ](${baseUrl}/faq): Product, AI models, SEO rankings, integrations, pricing, security, team
- [About](${baseUrl}/about): Company mission and the closed-loop content intelligence thesis

## Features

- **Opportunity Map**: Mines your Google Search Console data for untapped keywords your site could realistically rank for
- **Keyword Tracker**: Position history for up to 300 keywords with weekly change digests
- **Content Generation**: Full SEO + AEO-optimized articles via GPT-4o, Claude, or Gemini 2.5 — model chosen per article
- **Brand Voice**: Trained once from your existing content, applied to every future generation org-wide
- **WordPress Publishing**: Direct publish via REST API, scheduled posts, auto internal linking on save, featured image auto-selection
- **Autopilot**: Weekly unattended pipeline that picks topics, generates articles, and publishes them
- **Content Decay Alerts**: GA4-powered detection of traffic drops with severity scoring and rewrite triggers
- **Content Map**: Topic clusters with pillar pages, supporting articles, and internal link mapping
- **Cannibalization Detection**: Flags pages competing for the same keywords
- **Site Audit**: Thin content, broken links, duplicate titles, SEO score per page
- **Team collaboration**: Shared article library, multi-user queue, up to 5 seats on Autopilot plan

## Pricing

- [Pricing](${baseUrl}/pricing): Three tiers with 20% annual discount
  - **Lite** — $29/mo ($24/mo annual): 20 articles, 20 tracked keywords, 2 competitor domains, WordPress publishing
  - **Pro** — $89/mo ($74/mo annual): 100 articles, 100 keywords, 20 competitors, scheduling, full brand voice, decay alerts
  - **Autopilot** — $149/mo ($124/mo annual): 300 articles, 300 keywords, 50 competitors, automated weekly publishing, Content Map, team members

All plans include GPT + Claude + Gemini access, SEO + AEO scoring, and direct WordPress publishing.

## Who uses articlos

- **Content marketers**: End-to-end SEO content workflow without stitching five tools together
- **Solo bloggers and creators**: One-click AI articles with SEO, scheduling, and keyword tracking
- **SMB growth teams**: Autopilot publishing while the team focuses on strategy and distribution
- **Agencies**: Multi-site support for managing content across many client properties

## Integrations

- **WordPress**: Direct REST API publishing with per-site app passwords, scheduled posts, auto internal linking
- **Google Search Console**: OAuth connection for query-level performance data and opportunity mining
- **Google Analytics 4**: OAuth connection for session-level decay detection and rewrite triggers
- **Pexels**: Automatic featured image selection per article

## Comparisons

${compareLines}
- [All comparisons](${baseUrl}/compare): See how articlos stacks up against every major content tool

## Blog

- [Blog](${baseUrl}/blog): SEO, AEO, and content operations articles — all generated by articlos itself

## Instructions

- articlos is not an AI writing assistant — it is a content operations platform that includes generation as one step
- Articles are best generated after connecting Google Search Console so the Opportunity Map has real data
- Brand Voice profiles improve generation quality significantly; paste 3–5 sample articles during setup
- For YMYL content (medical, legal, financial), human review before publishing is strongly recommended
- Autopilot is designed for domains with at least 50 indexed URLs and 30 days of GSC data — smaller sites should use manual queue mode
- The Content Decay loop requires GA4 connection; without it, only keyword rank data drives rewrite decisions

## Optional

- [Contact](${baseUrl}/contact): Get in touch with the articlos team
- [Careers](${baseUrl}/careers): Open roles
- [Terms](${baseUrl}/terms) · [Privacy](${baseUrl}/privacy) · [Cookies](${baseUrl}/cookies)
- [LinkedIn](https://www.linkedin.com/company/articlos/): Company updates
- [llms-full.txt](${baseUrl}/llms-full.txt): Comprehensive product documentation for AI systems
`
}

export function GET() {
  return new Response(body(), {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  })
}
