import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — articlos',
  description: 'The terms that govern your use of articlos. Clear, fair, and written to be actually readable.',
  alternates: { canonical: '/terms' },
}

const sections = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    body: `By accessing or using articlos ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. These Terms apply to all visitors, users, and others who access or use the Service.

articlos is operated by PAPINGU L.L.C. ("Company", "we", "us", or "our"). We reserve the right to modify these Terms at any time. We will notify you of significant changes via email or a prominent notice within the Service. Your continued use after changes take effect constitutes acceptance of the updated Terms.`,
  },
  {
    id: 'service',
    title: '2. Description of Service',
    body: `articlos provides an AI-powered content intelligence platform that includes keyword research, content planning, article generation, publishing automation, analytics, and content optimization tools ("the Service").

We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time, with or without notice. We are not liable to you or any third party for any modification, suspension, or discontinuation of the Service.`,
  },
  {
    id: 'accounts',
    title: '3. Accounts and Registration',
    body: `You must create an account to use articlos. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to immediately notify us of any unauthorized use of your account.

You must provide accurate, complete, and current information during registration. You may not use a false identity, impersonate another person, or create an account if you are under 18 years of age.

We reserve the right to suspend or terminate your account if we reasonably believe you have violated these Terms.`,
  },
  {
    id: 'content',
    title: '4. User Content and AI-Generated Content',
    body: `You retain ownership of content you submit to the Service ("User Content"). By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free license to use, process, and display that content solely to provide the Service.

Content generated by our AI systems ("Generated Content") is provided to you under a non-exclusive license. You may use Generated Content for any lawful purpose, including commercial publication. However, you are solely responsible for reviewing, editing, and verifying all Generated Content before use.

We make no guarantees regarding the accuracy, completeness, originality, or suitability of Generated Content. AI-generated content may contain errors, inaccuracies, or factual mistakes. You acknowledge that you are responsible for all content published from your account.`,
  },
  {
    id: 'acceptable-use',
    title: '5. Acceptable Use',
    body: `You agree not to use the Service to:

• Generate or distribute spam, malware, phishing content, or any content that is deceptive, fraudulent, or misleading
• Violate any applicable law, regulation, or third-party rights, including intellectual property rights
• Circumvent, disable, or interfere with security features of the Service
• Use automated scripts to access the Service in a way that sends more requests than a human could reasonably produce
• Reverse engineer, decompile, or disassemble any part of the Service
• Resell, sublicense, or transfer access to the Service without our prior written consent
• Generate content that promotes violence, hatred, discrimination, or harassment

We reserve the right to investigate violations and take appropriate action, including account termination and legal action.`,
  },
  {
    id: 'payment',
    title: '6. Payment and Billing',
    body: `Paid plans are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by applicable law or as expressly stated in these Terms.

You authorize us to charge your payment method for all fees incurred. If payment fails, we may suspend your access until payment is resolved. Prices may change with 30 days' notice; continued use after a price change constitutes acceptance.

You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. We do not provide prorated refunds for unused periods.`,
  },
  {
    id: 'intellectual-property',
    title: '7. Intellectual Property',
    body: `The Service, including its design, functionality, trademarks, and underlying technology, is owned by PAPINGU L.L.C. and protected by intellectual property laws. Nothing in these Terms grants you any right to use our trademarks, logos, or brand assets without our prior written consent.

You may not copy, modify, distribute, sell, or create derivative works from any part of the Service without our explicit written permission.`,
  },
  {
    id: 'disclaimers',
    title: '8. Disclaimers and Limitation of Liability',
    body: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES.

TO THE MAXIMUM EXTENT PERMITTED BY LAW, PAPINGU L.L.C. SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS OR USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNTS PAID BY YOU IN THE 12 MONTHS PRECEDING THE CLAIM.`,
  },
  {
    id: 'termination',
    title: '9. Termination',
    body: `Either party may terminate the agreement at any time. We may suspend or terminate your access immediately if we believe you have materially violated these Terms.

Upon termination, your right to use the Service ceases immediately. We may retain your data as required by law or our data retention policies, after which it will be deleted in accordance with our Privacy Policy.`,
  },
  {
    id: 'governing-law',
    title: '10. Governing Law and Disputes',
    body: `These Terms are governed by the laws of the United States, without regard to conflict of law principles. Any disputes arising from these Terms or the Service shall be resolved through binding arbitration in accordance with the American Arbitration Association rules, except you may bring claims in small claims court if eligible.

You waive the right to participate in class action lawsuits or class-wide arbitration.`,
  },
  {
    id: 'contact',
    title: '11. Contact',
    body: `For questions about these Terms, contact us at hello@articlos.com. For legal notices, please direct correspondence to PAPINGU L.L.C.`,
  },
]

export default function TermsPage() {
  return (
    <>
      <Nav />

      <section style={{ padding: '120px 24px 64px', background: '#f9f9f8', borderBottom: '1px solid #e4e4e2' }}>
        <div style={{ maxWidth: 760, margin: '0 auto' }}>
          <div style={{
            fontSize: 11, fontWeight: 600, color: '#9b9b96',
            textTransform: 'uppercase', letterSpacing: '0.12em', marginBottom: 16,
          }}>
            Legal
          </div>
          <h1 style={{
            fontSize: 'clamp(28px, 5vw, 48px)',
            fontWeight: 700, letterSpacing: '-0.04em', color: '#0f0f0e', marginBottom: 12,
          }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, color: '#9b9b96' }}>
            Last updated: April 1, 2026 · Effective: April 1, 2026
          </p>
        </div>
      </section>

      <section style={{ padding: '64px 24px 96px', background: '#ffffff' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', display: 'flex', gap: 56, alignItems: 'flex-start' }} className="terms-layout">
          {/* TOC */}
          <aside style={{ width: 200, flexShrink: 0, position: 'sticky', top: 90 }} className="terms-toc">
            <div style={{ fontSize: 11, fontWeight: 600, color: '#9b9b96', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 12 }}>
              Contents
            </div>
            <nav style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {sections.map(s => (
                <a key={s.id} href={`#${s.id}`} className="toc-link">
                  {s.title.replace(/^\d+\.\s/, '')}
                </a>
              ))}
            </nav>
          </aside>

          {/* Content */}
          <div style={{ flex: 1, minWidth: 0 }}>
            {sections.map(s => (
              <div key={s.id} id={s.id} style={{ marginBottom: 48 }}>
                <h2 style={{
                  fontSize: 18, fontWeight: 700, letterSpacing: '-0.02em',
                  color: '#0f0f0e', marginBottom: 14,
                }}>
                  {s.title}
                </h2>
                {s.body.split('\n\n').map((para, i) => (
                  <p key={i} style={{
                    fontSize: 15, color: '#3d3d3a', lineHeight: 1.75, marginBottom: 14,
                    whiteSpace: 'pre-line',
                  }}>
                    {para}
                  </p>
                ))}
              </div>
            ))}
          </div>
        </div>
      </section>

      <Footer />

      <style>{`
        @media (max-width: 768px) {
          .terms-layout { flex-direction: column !important; gap: 32px !important; }
          .terms-toc { width: 100% !important; position: static !important; }
        }
      `}</style>
    </>
  )
}
