import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — articlos',
  description: 'The terms that govern your use of articlos. Clear, fair, and written to be actually readable.',
  alternates: { canonical: '/terms' },
}

const sections = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    body: `By accessing or using Articlos ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. These Terms constitute a legally binding agreement between you and PAPINGU L.L.C. ("Company", "we", "us", or "our") and apply to all visitors, users, and others who access or use the Service.

We reserve the right to modify these Terms at any time. We will notify you of significant changes via email or a prominent notice within the Service. Your continued use after changes take effect constitutes acceptance of the updated Terms.`,
  },
  {
    id: 'service',
    title: '2. Description of Service',
    body: `Articlos is an AI-powered content intelligence platform that helps users create SEO-optimised articles, manage content queues, analyse website performance, and automate publishing. The Service uses third-party AI models \u2014 including OpenAI GPT, Google Gemini, and Anthropic Claude \u2014 to generate content.

We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time, with or without notice. We are not liable to you or any third party for any modification, suspension, or discontinuation of the Service.`,
  },
  {
    id: 'eligibility',
    title: '3. Eligibility',
    body: `You must be at least 18 years of age to use the Service. By using the Service, you represent and warrant that you meet this requirement and have the legal capacity to enter into these Terms.`,
  },
  {
    id: 'accounts',
    title: '4. Accounts and Registration',
    body: `You must create an account to use Articlos. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to immediately notify us of any unauthorized use of your account. We are not liable for any loss or damage arising from your failure to safeguard your account.

You must provide accurate, complete, and current information during registration. You may not use a false identity, impersonate another person, or create an account if you are under 18 years of age.

We reserve the right to suspend or terminate your account if we reasonably believe you have violated these Terms.`,
  },
  {
    id: 'acceptable-use',
    title: '5. Acceptable Use',
    body: `You agree not to use the Service to:

\u2022 Generate or distribute spam, malware, phishing content, or any content that is deceptive, fraudulent, or misleading
\u2022 Violate any applicable law, regulation, or third-party rights, including intellectual property rights
\u2022 Generate content that is unlawful, harmful, defamatory, or infringing on third-party rights
\u2022 Circumvent, disable, or interfere with security features of the Service
\u2022 Use automated scripts or means beyond the API access we explicitly provide
\u2022 Reverse engineer, decompile, or disassemble any part of the Service
\u2022 Resell, sublicense, or transfer access to the Service without our prior written consent
\u2022 Generate content that promotes violence, hatred, discrimination, or harassment

We reserve the right to investigate violations and take appropriate action, including account termination and legal action.`,
  },
  {
    id: 'content',
    title: '6. User Content and AI-Generated Content',
    body: `You retain ownership of content you submit to the Service ("User Content"). By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free license to use, process, and display that content solely to provide the Service.

Content generated by our AI systems ("Generated Content") is provided to you under a non-exclusive license. You may use Generated Content for any lawful purpose, including commercial publication. However, you are solely responsible for reviewing, editing, and verifying all Generated Content before use.

We make no guarantees regarding the accuracy, completeness, originality, or suitability of Generated Content. AI-generated content may contain errors, inaccuracies, or factual mistakes. You acknowledge that you are responsible for all content published from your account.`,
  },
  {
    id: 'data-privacy',
    title: '7. Data & Privacy',
    body: `We collect and process data necessary to provide the Service, including your account information, content topics, and generated articles. We do not sell your personal data to third parties. Analytics data from Google Search Console and Google Analytics 4 is accessed only with your explicit authorisation and is used solely to provide analytics features within Articlos. For full details, see our Privacy Policy at articlos.com/privacy.`,
  },
  {
    id: 'payment',
    title: '8. Payment and Billing',
    body: `Paid plans are billed in advance on a monthly or annual basis. We invoice you at the start of each billing period and payment is due by direct bank transfer (SEPA or SWIFT) to the account specified on the invoice. Subscriptions automatically renew unless cancelled before the renewal date.

All fees are non-refundable except as required by applicable law. If payment is not received by the due date shown on the invoice, we may suspend your access until payment is resolved. Prices may change with 30 days' notice; continued use after a price change constitutes acceptance.

You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. We do not provide prorated refunds for unused periods.`,
  },
  {
    id: 'intellectual-property',
    title: '9. Intellectual Property',
    body: `The Service, including its design, functionality, trademarks, and underlying technology, is owned by PAPINGU L.L.C. and protected by intellectual property laws. You are granted a limited, non-exclusive, non-transferable licence to use the Service for its intended purpose.

Nothing in these Terms grants you any right to use our trademarks, logos, or brand assets without our prior written consent. You may not copy, modify, distribute, sell, or create derivative works from any part of the Service without our explicit written permission.`,
  },
  {
    id: 'indemnification',
    title: '10. Indemnification',
    body: `You agree to indemnify and hold harmless PAPINGU L.L.C. and its officers, directors, employees, and agents from any claims, liabilities, damages, losses, and expenses arising out of or related to your use of the Service or violation of these Terms.`,
  },
  {
    id: 'disclaimers',
    title: '11. Disclaimers and Limitation of Liability',
    body: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES.

TO THE MAXIMUM EXTENT PERMITTED BY LAW, PAPINGU L.L.C. SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS OR USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNTS PAID BY YOU IN THE 12 MONTHS PRECEDING THE CLAIM.`,
  },
  {
    id: 'termination',
    title: '12. Termination',
    body: `Either party may terminate the agreement at any time. We may suspend or terminate your access immediately if we believe you have materially violated these Terms. Upon termination, your right to use the Service ceases immediately. We may retain your data as required by law or our data retention policies, after which it will be deleted in accordance with our Privacy Policy.`,
  },
  {
    id: 'governing-law',
    title: '13. Governing Law and Disputes',
    body: `These Terms are governed by the laws of the Republic of Kosovo, without regard to conflict of law principles. Any disputes arising from these Terms or the use of the Service shall be subject to the exclusive jurisdiction of the competent courts of Kosovo.`,
  },
  {
    id: 'changes',
    title: '14. Changes to Terms',
    body: `We may update these Terms from time to time. We will notify you of material changes by email or via a prominent notice within the Service. Continued use of the Service after changes constitutes acceptance of the updated Terms.`,
  },
  {
    id: 'contact',
    title: '15. Contact',
    body: `For questions about these Terms, contact us at hello@articlos.com. For legal notices, please direct correspondence to PAPINGU L.L.C.`,
  },
]

export default function TermsPage() {
  return (
    <>
      <Nav />

      <section style={{ padding: '120px 24px 64px', background: 'var(--bg)', borderBottom: '1px solid var(--border)' }}>
        <div style={{ maxWidth: 760, margin: '0 auto' }}>
          <div style={{
            fontSize: 11, fontWeight: 600, color: 'var(--text-muted)',
            textTransform: 'uppercase', letterSpacing: '0.12em', marginBottom: 16,
          }}>
            Articlos &middot; PAPINGU L.L.C.
          </div>
          <h1 style={{
            fontSize: 'clamp(28px, 5vw, 48px)',
            fontWeight: 700, letterSpacing: '-0.04em', color: 'var(--text)', marginBottom: 12,
          }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, color: 'var(--text-muted)' }}>
            Last updated: April 24, 2026 &middot; Effective: April 24, 2026
          </p>
        </div>
      </section>

      <section style={{ padding: '64px 24px 96px', background: 'var(--surface)' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', display: 'flex', gap: 56, alignItems: 'flex-start' }} className="terms-layout">
          {/* TOC */}
          <aside style={{ width: 200, flexShrink: 0, position: 'sticky', top: 90 }} className="terms-toc">
            <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 12 }}>
              Contents
            </div>
            <nav style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {sections.map(s => (
                <a key={s.id} href={`#${s.id}`} className="toc-link">
                  {s.title.replace(/^\d+\.\s/, '')}
                </a>
              ))}
            </nav>
          </aside>

          {/* Content */}
          <div style={{ flex: 1, minWidth: 0 }}>
            {sections.map(s => (
              <div key={s.id} id={s.id} style={{ marginBottom: 48 }}>
                <h2 style={{
                  fontSize: 18, fontWeight: 700, letterSpacing: '-0.02em',
                  color: 'var(--text)', marginBottom: 14,
                }}>
                  {s.title}
                </h2>
                {s.body.split('\n\n').map((para, i) => (
                  <p key={i} style={{
                    fontSize: 15, color: 'var(--text)', lineHeight: 1.75, marginBottom: 14,
                    whiteSpace: 'pre-line',
                  }}>
                    {para}
                  </p>
                ))}
              </div>
            ))}
          </div>
        </div>
      </section>

      <Footer />

      <style>{`
        @media (max-width: 768px) {
          .terms-layout { flex-direction: column !important; gap: 32px !important; }
          .terms-toc { width: 100% !important; position: static !important; }
        }
      `}</style>
    </>
  )
}
